# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.7.0"

# Use postgresql as the database for Active Record
gem "pg", ">= 0.18", "< 2.0"
# Use Puma as the app server
gem "puma", "~> 4.3"

# Use grpc
gem "grpc-tools", "~> 1.27"
gem "grpc", "~> 1.28.0.pre2"
# Use pb
gem "google-protobuf", "~> 3.11", ">= 3.11.4"

# Use bulk insert
gem "activerecord-import", "~> 1.0", ">= 1.0.4"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", ">= 1.4.2", require: false

gem "activerecord", "~> 6.0"
gem "rake", "~> 13.0", ">= 13.0.1"

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
  gem "rspec", "~> 3.9"
  gem "rubocop-performance", "~> 1.5", ">= 1.5.2"
end

group :development do
end

group :test do
end
