# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("chat.proto", :syntax => :proto3) do
    add_message "serviveragent.railschat.com.protobuf.proto.CreateRoomRequest" do
      optional :user_id, :int32, 1
      optional :room_name, :string, 2
    end
    add_message "serviveragent.railschat.com.protobuf.proto.CreateRoomResponse" do
      optional :room_id, :int32, 1
    end
    add_message "serviveragent.railschat.com.protobuf.proto.UpdateRoomRequest" do
      optional :room, :message, 1, "serviveragent.railschat.com.protobuf.proto.Room"
    end
    add_message "serviveragent.railschat.com.protobuf.proto.UpdateRoomResponse" do
      optional :room_id, :int32, 1
    end
    add_message "serviveragent.railschat.com.protobuf.proto.UpdateRoomUserRequest" do
      optional :room_id, :int32, 1
      optional :user_id, :int32, 2
      repeated :user_ids, :int32, 3
    end
    add_message "serviveragent.railschat.com.protobuf.proto.UpdateRoomUserResponse" do
    end
    add_message "serviveragent.railschat.com.protobuf.proto.ListRoomRequest" do
      optional :user_id, :int32, 1
    end
    add_message "serviveragent.railschat.com.protobuf.proto.ListRoomResponse" do
      repeated :rooms, :message, 1, "serviveragent.railschat.com.protobuf.proto.Room"
    end
    add_message "serviveragent.railschat.com.protobuf.proto.Room" do
      optional :room_id, :int32, 1
      optional :user_id, :int32, 2
      optional :room_name, :string, 3
    end
    add_message "serviveragent.railschat.com.protobuf.proto.DeleteRoomRequest" do
      optional :room_id, :int32, 1
      optional :user_id, :int32, 2
    end
    add_message "serviveragent.railschat.com.protobuf.proto.DeleteRoomResponse" do
    end
    add_message "serviveragent.railschat.com.protobuf.proto.UpdateUserRequest" do
      optional :user, :message, 1, "serviveragent.railschat.com.protobuf.proto.User"
    end
    add_message "serviveragent.railschat.com.protobuf.proto.User" do
      optional :user_id, :int32, 1
      optional :user_name, :string, 2
    end
    add_message "serviveragent.railschat.com.protobuf.proto.UpdateUserResponse" do
    end
    add_message "serviveragent.railschat.com.protobuf.proto.ListUserRequest" do
      repeated :users, :message, 1, "serviveragent.railschat.com.protobuf.proto.User"
    end
    add_message "serviveragent.railschat.com.protobuf.proto.ListUserResponse" do
    end
    add_message "serviveragent.railschat.com.protobuf.proto.DeleteUserRequest" do
      optional :user_id, :int32, 1
    end
    add_message "serviveragent.railschat.com.protobuf.proto.DeleteUserResponse" do
    end
    add_message "serviveragent.railschat.com.protobuf.proto.CreateMessageRequest" do
      optional :user_id, :int32, 1
      optional :room_id, :int32, 2
      optional :message, :string, 3
    end
    add_message "serviveragent.railschat.com.protobuf.proto.CreateMessageResponse" do
    end
    add_message "serviveragent.railschat.com.protobuf.proto.UpdateMessageRequest" do
      optional :message_id, :int32, 1
      optional :user_id, :int32, 2
      optional :message, :string, 3
    end
    add_message "serviveragent.railschat.com.protobuf.proto.UpdateMessageResponse" do
    end
    add_message "serviveragent.railschat.com.protobuf.proto.ListMessageRequest" do
      optional :room_id, :int32, 1
    end
    add_message "serviveragent.railschat.com.protobuf.proto.ListMessageResponse" do
      repeated :messages, :message, 1, "serviveragent.railschat.com.protobuf.proto.Message"
    end
    add_message "serviveragent.railschat.com.protobuf.proto.Message" do
      optional :message_id, :int32, 1
      optional :user_id, :int32, 2
      optional :message, :string, 3
    end
    add_message "serviveragent.railschat.com.protobuf.proto.DeleteMessageRequest" do
      optional :message_id, :int32, 1
      optional :user_id, :int32, 2
    end
    add_message "serviveragent.railschat.com.protobuf.proto.DeleteMessageResponse" do
    end
  end
end

module Serviveragent
  module Railschat
    module Com
      module Protobuf
        module Proto
          CreateRoomRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("serviveragent.railschat.com.protobuf.proto.CreateRoomRequest").msgclass
          CreateRoomResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("serviveragent.railschat.com.protobuf.proto.CreateRoomResponse").msgclass
          UpdateRoomRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("serviveragent.railschat.com.protobuf.proto.UpdateRoomRequest").msgclass
          UpdateRoomResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("serviveragent.railschat.com.protobuf.proto.UpdateRoomResponse").msgclass
          UpdateRoomUserRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("serviveragent.railschat.com.protobuf.proto.UpdateRoomUserRequest").msgclass
          UpdateRoomUserResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("serviveragent.railschat.com.protobuf.proto.UpdateRoomUserResponse").msgclass
          ListRoomRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("serviveragent.railschat.com.protobuf.proto.ListRoomRequest").msgclass
          ListRoomResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("serviveragent.railschat.com.protobuf.proto.ListRoomResponse").msgclass
          Room = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("serviveragent.railschat.com.protobuf.proto.Room").msgclass
          DeleteRoomRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("serviveragent.railschat.com.protobuf.proto.DeleteRoomRequest").msgclass
          DeleteRoomResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("serviveragent.railschat.com.protobuf.proto.DeleteRoomResponse").msgclass
          UpdateUserRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("serviveragent.railschat.com.protobuf.proto.UpdateUserRequest").msgclass
          User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("serviveragent.railschat.com.protobuf.proto.User").msgclass
          UpdateUserResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("serviveragent.railschat.com.protobuf.proto.UpdateUserResponse").msgclass
          ListUserRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("serviveragent.railschat.com.protobuf.proto.ListUserRequest").msgclass
          ListUserResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("serviveragent.railschat.com.protobuf.proto.ListUserResponse").msgclass
          DeleteUserRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("serviveragent.railschat.com.protobuf.proto.DeleteUserRequest").msgclass
          DeleteUserResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("serviveragent.railschat.com.protobuf.proto.DeleteUserResponse").msgclass
          CreateMessageRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("serviveragent.railschat.com.protobuf.proto.CreateMessageRequest").msgclass
          CreateMessageResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("serviveragent.railschat.com.protobuf.proto.CreateMessageResponse").msgclass
          UpdateMessageRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("serviveragent.railschat.com.protobuf.proto.UpdateMessageRequest").msgclass
          UpdateMessageResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("serviveragent.railschat.com.protobuf.proto.UpdateMessageResponse").msgclass
          ListMessageRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("serviveragent.railschat.com.protobuf.proto.ListMessageRequest").msgclass
          ListMessageResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("serviveragent.railschat.com.protobuf.proto.ListMessageResponse").msgclass
          Message = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("serviveragent.railschat.com.protobuf.proto.Message").msgclass
          DeleteMessageRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("serviveragent.railschat.com.protobuf.proto.DeleteMessageRequest").msgclass
          DeleteMessageResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("serviveragent.railschat.com.protobuf.proto.DeleteMessageResponse").msgclass
        end
      end
    end
  end
end
