# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: router.proto for package 'serviveragent.railschat.com.protobuf.proto'

require 'grpc'
require 'router_pb'

module Serviveragent
  module Railschat
    module Com
      module Protobuf
        module Proto
          module RoomService
            class Service

              include GRPC::GenericService

              self.marshal_class_method = :encode
              self.unmarshal_class_method = :decode
              self.service_name = 'serviveragent.railschat.com.protobuf.proto.RoomService'

              rpc :CreateRoom, CreateRoomRequest, CreateRoomResponse
              rpc :UpdateRoom, UpdateRoomRequest, UpdateRoomResponse
              rpc :UpdateUser, UpdateRoomUserRequest, UpdateRoomUserResponse
              rpc :List, ListRoomRequest, ListRoomResponse
              rpc :Delete, DeleteRoomRequest, DeleteRoomResponse
            end

            Stub = Service.rpc_stub_class
          end
          module UserService
            class Service

              include GRPC::GenericService

              self.marshal_class_method = :encode
              self.unmarshal_class_method = :decode
              self.service_name = 'serviveragent.railschat.com.protobuf.proto.UserService'

              rpc :Update, UpdateUserRequest, UpdateUserResponse
              # todo: streamのAPIも作る
              rpc :List, ListUserRequest, ListUserResponse
              rpc :Delete, DeleteUserRequest, DeleteUserResponse
            end

            Stub = Service.rpc_stub_class
          end
          # create
          # 後で考える
          module MessageService
            class Service

              include GRPC::GenericService

              self.marshal_class_method = :encode
              self.unmarshal_class_method = :decode
              self.service_name = 'serviveragent.railschat.com.protobuf.proto.MessageService'

              rpc :Create, CreateMessageRequest, CreateMessageResponse
              rpc :Update, UpdateMessageRequest, UpdateMessageResponse
              rpc :List, ListMessageRequest, ListMessageResponse
              rpc :Delete, DeleteMessageRequest, DeleteMessageResponse
            end

            Stub = Service.rpc_stub_class
          end
        end
      end
    end
  end
end
